services:
  - type: web_service
    name: college-platform-backend
    env: node
    region: oregon
    plan: starter
    branch: main
    root: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /health
